apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/osd-example-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" &&
      target_branch == "main" 
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: osd-example-operator-main
    appstudio.openshift.io/component: e2e-main
    pipelines.appstudio.openshift.io/type: build
  name: e2e-main-on-push
  namespace: oeo-cicada-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/oeo-cicada-tenant/osd-example-operator-main/osd-example-operator-main/e2e:{{revision}}
  - name: dockerfile
    value: osde2e/Dockerfile
  - name: path-context
    value: .
  - name: major-version
    value: "0"
  - name: minor-version
    value: "2"
  - name: channel
    value: stable
  - name: package-name
    value: osd-example-operator
  pipelineRef:
    params:
    - name: url
      value: https://github.com/openshift/boilerplate
    - name: revision
      value: master
    - name: pathInRepo
      value: pipelines/bundle-builder/pipeline.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-e2e-main
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
